version: "3"
services:
  jobmanager:
    image: apache/flink:1.13.0-scala_2.11-java11
    command: jobmanager
    hostname: flinkjobmanger
    environment:
      - |
        CONFIG=
        kafka-io:
          - name: action
            type: source
            topic: TodoAction
            properties:
              bootstrap.servers: kafka:9093
              group.id: todo-action
          - name: reaction
            type: sink
            topic: TodoReaction
            semantic: AT_LEAST_ONCE
            properties:
              bootstrap.servers: kafka:9093
          - name: txlog
            type: sink
            topic: TodoTxLog
            semantic: EXACTLY_ONCE
            properties:
              bootstrap.servers: kafka:9093
        checkpoints:
          enabled: true
          interval: 10000
          #mode: AT_LEAST_ONCE
          mode: EXACTLY_ONCE
          timeout: 900000
          pause: 1000
          concurrent: 1
          externalization: true

      - |
        FLINK_PROPERTIES=
        classloader.resolve-order: parent-first
        jobmanager.rpc.address: flinkjobmanger
        state.backend: rocksdb
        state.checkpoints.dir: file:/opt/flink/data/todo-app/checkpointing
        state.savepoints.dir: file:/opt/flink/data/todo-app/savepointing
        state.backend.incremental: true
        state.backend.rocksdb.timer-service.factory: ROCKSDB
        state.backend.rocksdb.localdir: /opt/flink/data/todo-app/state-rocksdb
        web.tmpdir: /opt/flink/submit-job
        rest.flamegraph.enabled: true
    ports:
      - "8181:8081"
    volumes:
      - flink:/opt/flink/data
    networks:
      - "dev"
  taskmanager:
    image: apache/flink:1.13.0-scala_2.11-java11
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        classloader.resolve-order: parent-first
        jobmanager.rpc.address: flinkjobmanger
        state.backend: rocksdb
        state.checkpoints.dir: file:/opt/flink/data/todo-app/checkpointing
        state.savepoints.dir: file:/opt/flink/data/todo-app/savepointing
        state.backend.incremental: true
        state.backend.rocksdb.timer-service.factory: ROCKSDB
        state.backend.rocksdb.localdir: /opt/flink/data/todo-app/state-rocksdb
        rest.flamegraph.enabled: true
    volumes:
      - "flink:/opt/flink/data"
    networks:
      - "dev"

volumes:
  flink:
    external: true

networks:
  dev:
    external:
      name: ${TODO_APP_NETWORK:-todo-app}