version: "3"
services:
  jobmanager:
    image: ${FLINK_IMAGE}
    command: jobmanager
    hostname: flinkjobmanger
    environment:
      - |
        FLINK_PROPERTIES=
        classloader.resolve-order: parent-first
        jobmanager.rpc.address: flinkjobmanger
        state.backend: rocksdb
        state.checkpoints.dir: file:/opt/flink/data/todo-app/checkpointing
        state.savepoints.dir: file:/opt/flink/data/todo-app/savepointing
        state.checkpoint-storage: filesystem
        state.backend.incremental: true
        state.backend.rocksdb.timer-service.factory: ROCKSDB
        state.backend.rocksdb.localdir: /opt/flink/data/todo-app/state-rocksdb
        web.tmpdir: /opt/flink/submit-job
        rest.flamegraph.enabled: true
    ports:
      - "8181:8081"
    volumes:
      - flink:/opt/flink/data
      - ../target/todo-app.jar:/opt/flink/todo-app.jar
      - ./todo-app.yaml:/opt/flink/todo-app.yaml
    networks:
      - dev
  taskmanager:
    image: ${FLINK_IMAGE}
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        classloader.resolve-order: parent-first
        jobmanager.rpc.address: flinkjobmanger
        state.backend: rocksdb
        state.checkpoints.dir: file:/opt/flink/data/todo-app/checkpointing
        state.savepoints.dir: file:/opt/flink/data/todo-app/savepointing
        state.checkpoint-storage: filesystem
        state.backend.incremental: true
        state.backend.rocksdb.timer-service.factory: ROCKSDB
        state.backend.rocksdb.localdir: /opt/flink/data/todo-app/state-rocksdb
        rest.flamegraph.enabled: true
        taskmanager.numberOfTaskSlots: 5
    volumes:
      - "flink:/opt/flink/data"
    networks:
      - dev

volumes:
  flink:
    external: true

networks:
  dev:
    external:
      name: ${TODO_APP_NETWORK:-todo-app}