version: "3"
services:
  flink:
    image: ${FLINK_IMAGE}
    command: ha-cluster
    hostname: todo-app-flink
    environment:
      - |
        FLINK_PROPERTIES=
        classloader.resolve-order: parent-first
        rest.flamegraph.enabled: true
        env.java.opts.jobmanager: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
        env.java.opts.taskmanager: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
      - _FLINK_RUN_JOB=./todo-app.jar --config /opt/flink/todo-app.yaml --scale 1
      - |
        SCRIPT=
        ls -la;
        flink list;
        sleep 15;
    ports:
      - 8181:8081
      - 61208:61208
    volumes:
      - todo-app:/usr/share/zookeeper
      - todo-app:/usr/share/flink
      - ../target/todo-app.jar:/opt/flink/todo-app.jar
      - ./todo-app.yaml:/opt/flink/todo-app.yaml
    networks:
      - dev
volumes:
  todo-app:
    driver: local

networks:
  dev:
    external:
      name: ${TODO_APP_NETWORK:-todo-app}