version: "3"
services:
  gateway:
    image: ${GATEWAY_IMAGE}
    environment:
     - BROKER=kafka:9093
     - PUBLISH_TOPIC=TodoAction
     - SUBSCRIBE_TOPIC=TodoReaction
     - SUBSCRIBE_GROUP_ID=todo-gateway
     - TIMEOUT=60
    ports:
      - ${PORT_GATEWAY_API}:8080
    depends_on:
     - kafka
    networks:
      - dev
  flink:
    image: ${FLINK_IMAGE}
    command: cluster
    hostname: todo-app-flink
    environment:
      - |
        FLINK_PROPERTIES=
        classloader.resolve-order: parent-first
        taskmanager.numberOfTaskSlots: 5
        parallelism.default: 2
        rest.flamegraph.enabled: true
        env.java.opts.jobmanager: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
        env.java.opts.taskmanager: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
      - FLINK_RUN_JOB=./todo-app.jar --config ./todo-app.yaml
      - |
        SCRIPT=
        ls -la;
        flink list;
        sleep 15;
    ports:
      - ${PORT_FLINK_UI}:8081
      - ${PORT_DEBUG_TM}:5006
    volumes:
      - todo-app:/usr/share/zookeeper
      - todo-app:/usr/share/flink
      - ../target/todo-app.jar:/opt/flink/todo-app.jar
      - ./todo-app.yaml:/opt/flink/todo-app.yaml
    depends_on:
     - kafka
    networks:
      - dev
  kafka:
    image: s7i/kafka
    environment:
      - SCRIPT=/opt/env-setup.sh > script.log;
    ports:
      - ${PORT_RANGE}:61208
      - ${PORT_RANGE}:9092
      - ${PORT_RANGE}:2181
    networks:
     - dev
    volumes:
     - todo-app:/data
     - /var/run/docker.sock:/var/run/docker.sock
     - ./env-setup.sh:/opt/env-setup.sh

    restart: unless-stopped

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
     - ${PORT_KAFDROP}:9000
    depends_on:
     - kafka
    networks:
     - dev
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
      JVM_OPTS: -Xms32M -Xmx64M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
      SERVER_SERVLET_CONTEXTPATH: /
volumes:
  todo-app:
    driver: local

networks:
  dev:
    name: ${TODO_APP_NETWORK:-todo-app}